//GuessMyNumber - The classic number guessing game

#include <iostream>
#include <cstdlib>
#include <ctime>
#include <windows.h>

using namespace std;

//The player tries to guess a random number generated by the computer
void humanFinder() {

  //Seed the random number generator
  srand(static_cast<unsigned int>(time(0)));

  //get a random number between 1-100
  int secretNumber = rand() % 100 + 1;
  int tries = 0;
  int guess;

  cout << "\tWelcome to Guess My Number\n\n";

  do {
    cout << "Enter a guess (1-100): ";
    cin >> guess;
    ++tries;

    if(guess > secretNumber) {
      cout << "Too high!\n\n";
    } else if(guess < secretNumber) {
      cout << "Too low!\n\n";
    } else {
      cout << "\nThat's it! You got it in " << tries << " guesses!\n";
    }
  } while(guess != secretNumber);
}

//The computer tries to guess a number given by the player
void computerFinder() {

  //Seed the random number generator
  //srand(static_cast<unsigned int>(time(0)));

  //get a random number between 1-100
  int guess = rand() % 100 + 1;
  int secretNumber;
  int tries = 0;
  bool flag=true;

  cout << "Enter a number (1-1000): ";
  cin >> secretNumber;

  do {
    ++tries;

    guess = rand() % 1000 + 1;
    cout << guess;

    if(guess > secretNumber) {
      cout << "Too high!\n";
    } else if(guess < secretNumber) {
      cout << "Too low!\n";
    } else {
      cout << "\nThat's it! computer found your number in " << tries << " guesses!\n";
      //Sleep(1000);
      //tries = 0;
    }
  }while(guess != secretNumber); //while(flag);
}


int main() {
  int selection;
  cout << "\tWelcome to Guess My Number\n\n";
  cout << "Choose game mode \n--Press 1 if you want to guess the number \n--Press 2 for computer guessing your number\n";
  cin >> selection;

  switch (selection) {
    case 1:
      humanFinder();
      break;
    case 2:
      computerFinder();
      break;
    default:
      break;
  }


  cout << "\t\t!!GAME OVER!!\n\n";
  return 0;
}

